repos:
-   repo: local
    hooks:
    -   id: check_requirements
        name: check requirements
        description: Check if requirements are made or make it
        always_run: true
        entry: pre_commit_hooks/check_requirements.py
        language: script
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        verbose: true
        exclude: (setup.py|check-requirements.py|__init__.py|tests/)
        args: [
            --verbose,
            --ignore-init-module,
            --ignore-init-method,
            -i,
            --fail-under=0
            ]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args:
        - --line-length=120
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
        - --max-line-length=120
        - --ignore=E203,W503
        - --max-complexity=10
        - --select=E9,F63,F7,F82
        - --show-source
        - --statistics
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
# -   repo: local
#     hooks:
#     -   id: check_requirements
#         name: check requirements
#         description: Check if requirements are made or make it
#         entry: pre_commit_hooks/check_requirements.py
#         language: script
#         types: [python]
